apiVersion: v1
baseDomain: kni.syseng.devcluster.openshift.com
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      zones:
      - us-west-2a
      type: m5.xlarge
  replicas: 3
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    aws:
      zones:
      - us-west-2a
      type: m5.xlarge
  replicas: 3
metadata:
  name: acm-test-cluster-managed
networking:
  clusterNetwork:
  - cidr: 10.132.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.1.0.0/16
  serviceNetwork:
  - 172.31.0.0/16
platform:
  aws:
    region: us-west-2
pullSecret: 'Add your pull secret here'
## The default SSH key that will be programmed for `core` user.
sshKey: |
  Add you ssh key here